site_name: MPI.js
site_url: https://the-parallel-gods.github.io

theme:
  font:
    text: Roboto
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    # - toc.integrate
    - navigation.expand
    - navigation.top

extra:
  consent:
    title: Cookie consent
    description: >-
      We don't use cookies, is that okay?

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: >
  Copyright &copy; 2024 the-parallel-gods

nav:
  - Home: home.md
  - Proposal: proposal.md
  - Docs: docs.md
